// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimplyBudgetWeb.Data;

#nullable disable

namespace SimplyBudgetWeb.Data.Migrations
{
    [DbContext(typeof(BudgetWebContext))]
    [Migration("20260928012437_AddReceipts")]
    partial class AddReceipts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SimplyBudget")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimplyBudgetShared.Data.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IsDefault");

                    b.ToTable("Account", "SimplyBudget");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.ExpenseCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AccountID")
                        .HasColumnType("int");

                    b.Property<int>("BudgetedAmount")
                        .HasColumnType("int");

                    b.Property<int>("BudgetedPercentage")
                        .HasColumnType("int");

                    b.Property<int?>("Cap")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentBalance")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("CategoryName");

                    b.ToTable("ExpenseCategory", "SimplyBudget");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.ExpenseCategoryItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ExpenseCategoryItem", "SimplyBudget");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.ExpenseCategoryItemDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ExpenseCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ExpenseCategoryItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IgnoreBudget")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("ExpenseCategoryItemId");

                    b.ToTable("ExpenseCategoryItemDetail", "SimplyBudget");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.ExpenseCategoryRule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ExpenseCategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("MaximumAmount")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumAmount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleRegex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ExpenseCategoryID");

                    b.ToTable("ExpenseCategoryRules", "SimplyBudget");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.ExternalLinkRule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleRegex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ExternalLinkRule", "SimplyBudget");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.Metadata", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MetaData", "SimplyBudget");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.PendingExpense", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDebit")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuggestedCategoryId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("Date");

                    b.HasIndex("SuggestedCategoryId");

                    b.ToTable("PendingExpense", "SimplyBudget");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.PendingExpenseAssignee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNameCustomized")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ObjectId")
                        .IsUnique();

                    b.ToTable("PendingExpenseAssignee", "SimplyBudget");
                });

            modelBuilder.Entity("SimplyBudgetWeb.Data.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessingMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("TotalAmountCents")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TotalAmountCents", "TransactionDate");

                    b.ToTable("Receipt", "SimplyBudget");
                });

            modelBuilder.Entity("SimplyBudgetWeb.Data.ReceiptExpenseLink", b =>
                {
                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<int>("ExpenseCategoryItemId")
                        .HasColumnType("int");

                    b.HasKey("ReceiptId");

                    b.HasIndex("ExpenseCategoryItemId")
                        .IsUnique();

                    b.ToTable("ReceiptExpenseLink", "SimplyBudget");
                });

            modelBuilder.Entity("SimplyBudgetWeb.Data.ReceiptLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountCents")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptLineItem", "SimplyBudget");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.ExpenseCategory", b =>
                {
                    b.HasOne("SimplyBudgetShared.Data.Account", "Account")
                        .WithMany("ExpenseCategories")
                        .HasForeignKey("AccountID");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.ExpenseCategoryItemDetail", b =>
                {
                    b.HasOne("SimplyBudgetShared.Data.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimplyBudgetShared.Data.ExpenseCategoryItem", "ExpenseCategoryItem")
                        .WithMany("Details")
                        .HasForeignKey("ExpenseCategoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");

                    b.Navigation("ExpenseCategoryItem");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.ExpenseCategoryRule", b =>
                {
                    b.HasOne("SimplyBudgetShared.Data.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryID");

                    b.Navigation("ExpenseCategory");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.PendingExpense", b =>
                {
                    b.HasOne("SimplyBudgetShared.Data.PendingExpenseAssignee", "Assignee")
                        .WithMany("PendingExpenses")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SimplyBudgetShared.Data.ExpenseCategory", "SuggestedCategory")
                        .WithMany()
                        .HasForeignKey("SuggestedCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assignee");

                    b.Navigation("SuggestedCategory");
                });

            modelBuilder.Entity("SimplyBudgetWeb.Data.ReceiptExpenseLink", b =>
                {
                    b.HasOne("SimplyBudgetShared.Data.ExpenseCategoryItem", "ExpenseCategoryItem")
                        .WithOne()
                        .HasForeignKey("SimplyBudgetWeb.Data.ReceiptExpenseLink", "ExpenseCategoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimplyBudgetWeb.Data.Receipt", "Receipt")
                        .WithOne()
                        .HasForeignKey("SimplyBudgetWeb.Data.ReceiptExpenseLink", "ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategoryItem");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("SimplyBudgetWeb.Data.ReceiptLineItem", b =>
                {
                    b.HasOne("SimplyBudgetWeb.Data.Receipt", "Receipt")
                        .WithMany("LineItems")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.Account", b =>
                {
                    b.Navigation("ExpenseCategories");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.ExpenseCategoryItem", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("SimplyBudgetShared.Data.PendingExpenseAssignee", b =>
                {
                    b.Navigation("PendingExpenses");
                });

            modelBuilder.Entity("SimplyBudgetWeb.Data.Receipt", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
