name: .NET

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '1.0.0'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.x
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Restore Tools
      run: dotnet tool restore

    - name: Publish
      run: dotnet publish SimplyBudgetDesktop\SimplyBudgetDesktop.csproj -c Release --self-contained -r win-x64 -o .\publish

    - name: vpk pack
      if: github.event_name == 'workflow_dispatch'
      run: dotnet vpk pack --packId keboo.simplybudget --packVersion ${{ inputs.version }} --packDir .\publish --mainExe SimplyBudget.exe

    - name: Push Release
      if: github.event_name == 'workflow_dispatch'
      run: dotnet vpk publish -o .\publish --waitForLive --api-key ${{ secrets.VPK_API_KEY }}



